name: Base Issue
description: Suggest a new issue or improvement.
title: "[Issue]: "
labels: ["enhancement"]

assignees:
  - Alonsovn

body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of the feature you are requesting.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🧠 Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
