name: 💬 Question / Discussion
description: Ask a question or start a discussion.
title: "[Question]: "
labels: ["question"]

assignees:
  - Alonsovn

body:
  - type: input
    id: topic
    attributes:
      label: ❓ Topic
      description: What would you like to ask or discuss?
      placeholder: "Your question or discussion topic"
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 📝 Background
      description: Provide any background information or context.
    validations:
      required: false

  - type: input
    id: ticket
    attributes:
      label: 🗾 Ticket (if applicable)
      description: Reference to a related ticket, if any.
      placeholder: "Ticket number or link"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: 🧠 Additional Context
      description: Add any other context or related information here.
    validations:
      required: false
